### ISSUE TITLE
Error Message when using advancedForm module in frontend

### ISSUE THREAD

**Issue by Lotto23** [oveleon/contao-advanced-form-bundle#1]
request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 4 passed to ConditionalFormFields::loadFormField() must be an instance of Contao\Form, instance of Oveleon\ContaoAdvancedFormBundle\AdvancedForm given, called in

**Comment by eki89** [comment]
Hello Lotto23,
the architecture of the advanced-form bundle causes some problems since Contao 4.10. The main issue is the incompatibility with other third party bundles that extend the form generator. The advanced form must be fundamentally rewritten to solve these problems. The bundle will not continue to work with Contao 4.10 because of type safety and will be replaced by a new bundle for multiple form pages with conditions.

**Comment by doishub** [comment]
see https://github.com/oveleon/contao-advanced-form.
